### ISSUE TITLE
Sample vs Sampling Distribution Confusion

### ISSUE THREAD

**Issue by andrewwhitman** [learn-co-curriculum/dsc-central-limit-theorem-lab#2]
## Link to Canvas

https://github.com/learn-co-curriculum/dsc-central-limit-theorem-lab

## Issue Subtype

- [x ] Master branch code
- [x ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [x ] Instructions unclear
- [ ] Other (explain below)

### Source

```
The examples are numerous throughout this lab. Here's one.
Before we can make use of the normal distribution, we need to first confirm that our data is normally distributed. If it is not, then we'll need to use the Central Limit Theorem to create a sample distribution of sample means that will be normally distributed.
```

### Concern

The lab refers to a _sample_ distribution of sample means instead of a _sampling_ distribution of sample means. The _sampling_ distribution language is used in the Objectives and then reverts to _sample_ throughout the lab. Two labs later in the Confidence Intervals Lab, a distinction is called out between _sample_ and _sampling_ distributions, but this lab seems to ignore this difference.

## (Optional) Proposed Solution

Replace instances of sample distribution with sampling distribution when describing the distribution of sample means for consistency with other course material.

## What OS Are You Using?

- [ ] OS X
- [x ] Windows
- [ ] WSL
- [ ] Linux
- [ ] IllumiDesk

**Comment by bpurdy-ds** [comment]
Correct, this is incorrect. I'll replace _sample_ with _sampling_ as necessary.

**Comment by bpurdy-ds** [comment]
Corrected all 15 or so. Closed with commit: https://github.com/learn-co-curriculum/dsc-central-limit-theorem-lab/issues/2#issue-1003009851
