### ISSUE TITLE
The additional resources link most of them  don't work!

### ISSUE THREAD

**Issue by RoseKyalo** [learn-co-curriculum/dsc-central-limit-theorem-lab#3]
## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```

```

## What OS Are You Using?

- [ ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by Cheffrey2000** [comment]
These external links have been removed, as they were not necessary.
