### ISSUE TITLE
Code missing value

### ISSUE THREAD

**Issue by andreihushcha** [learn-co-curriculum/dsc-central-limit-theorem-lab#4]
## Link to Canvas

https://learning.flatironschool.com/courses/6852/assignments/251031?module_item_id=592806
https://github.com/learn-co-curriculum/dsc-central-limit-theorem-lab/tree/master

## Issue Subtype

- [x] Master branch code
- [x] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [ ] Instructions unclear
- [ ] Other (explain below)

### Source

```
1) Missing "seed" value = 0 in code in all branches.
2) The result of running code in solution branch does not correspond to the right answer.
```

### Concern

![Screenshot 2023-10-14 194908](https://github.com/learn-co-curriculum/dsc-central-limit-theorem-lab/assets/117996551/8c702688-088f-40e0-9489-c71c09b0869a)
![Screenshot 2023-10-14 190904](https://github.com/learn-co-curriculum/dsc-central-limit-theorem-lab/assets/117996551/ef2f97fa-9463-4671-9499-df7032a05e25)

## (Optional) Proposed Solution

test_sample2 = get_sample(data, 30, 0)

## What OS Are You Using?

- [ ] OS X
- [x] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
There were discrepancies between the various branches. Now fixed, hopefully. 
Thank you bringing this to our attention.
